name: run m-outlet-scheduler

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '20 11 * * *' # At 11.20 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: install tesseract-ocr
        run: sudo apt-get install tesseract-ocr
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute py script
        env:
          SENDER: ${{ secrets.SENDER }}
          RECEIPIENT: ${{ secrets.RECEIPIENT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GD_PROJECT_ID: ${{ secrets.GD_PROJECT_ID }}
          GD_PRIVATE_KEY_ID: ${{ secrets.GD_PRIVATE_KEY_ID }}
          GD_PRIVATE_KEY: ${{ secrets.GD_PRIVATE_KEY }}
          GD_CLIENT_EMAIL: ${{ secrets.GD_CLIENT_EMAIL }}
          GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        run: python m-scheduler.py
      
